# Site settings
title: Cards from the Edge
#header-img: img/home-bg.jpg
email: jotpublishing@gmail.com
description: "Cards from the Edge will take you on a short journey of creativity and love from one friend to another by way of full STOPs and smileys!"
url: "http://cardsfromtheedge.co.uk"
baseurl: ""

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Jo Turner

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: "https://twitter.com/cardsfromtheedge"
  - title: facebook
    url: "https://www.facebook.com/CardsfromtheEdge"

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
gems: ["jekyll-paginate"]